### ISSUE TITLE
Create our own istio.yaml for riff

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#1236]
In light of https://github.com/knative/serving/issues/3670 we should start investigating curating our own `istio.yaml` directly from Istio releases

**Comment by scothis** [comment]
While we're at it, we should look at using using something more like istio light (or Solo Gloo), which act as an ingress controller rather than a full service mesh. Avoiding the sidecar injection/init will help significantly with pod startup times. We should keep the full mesh available as an option for users who need its capabilities.

**Comment by scothis** [comment]
Done in projectriff/charts#8
