### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by sdeleuze** [projectriff/riff#283]
Hey, I would be interested to contribute Kotlin support to Riff. This support would be based on the upcoming [Kotlin Scripting support improvements](https://github.com/Kotlin/KEEP/blob/scripting/proposals/scripting-support.md) which is designed to overcome current limitations (no imports, no caching between execution) and should allow to target various platforms (JVM and Native) in a consistent way.

Prototypes of this new support [seems to be around the corner](https://github.com/Kotlin/KEEP/issues/75#issuecomment-360834063), if it takes too much time we may do some progress using [kscript](https://github.com/holgerbrandl/kscript) potentially.

Supporting Kotlin/JVM via the current Java Riff support is possible and maybe already works since it is equivalent to Java in term of packaging, so it could be low hanging fruit for the short term. I will check if that works or not. But I do think Kotlin Scripting enhanced support will be a much more suitable foundation for Riff support.

Any thoughts or interest about this topic?

**Comment by jldec** [comment]
Definitely interested - thanks @sdeleuze!

cc @ericbottard @dsyer @markfisher

**Comment by apatrida** [comment]
Have you looked at using Kotlin Lambda's as functions (You could also do this with Java Lambdas)?  You do not need scripting, you can serialize the Lambda to a form that can be shipped, added to a sidecar and executed (and securely as well against white-listed methods).  

See: 
https://github.com/kohesive/chillambda (serializing Lambda's from client code as scripts)
https://github.com/kohesive/cuarentena (security of code via bytecode analysis)

And an example usage as binary scripts in Elasticsearch:
https://github.com/kohesive/elasticsearch-lang-kotlin

There was also an experiment done where a generic AWS Lambda was created, that could run scripts based on their desired context, the context deciding what access they were allowed via a predefined API and security rules.  Then the client code would just send a message that included the Kotlin lambda and it would be verified and executed by the AWS Lambda as the message passed by.  This allowed queuing of data + functions to be executed at any scale.  Then this was tried to basically have a Lambda that merged incoming data with predefined "binary scripts" (Kotlin serialized Lambdas) and pass along to the executor function, so that only the data was sent by clients, merged with the lambda, and executed at scale.

I'm the maintainer of the projects and they are nearing release, along with more samples.  So if there is interest, let's see how they could work here.

**Comment by sdeleuze** [comment]
Thanks @apatrida, I was not aware of these interesting capabilities. That's said, we are probably going to start with something simpler but I will contact you after that to explore your proposal for scripting support.

After more thoughts, my proposal is to start simple by Kotlin/JVM support on `java-function-invoker`, I have created https://github.com/projectriff/java-function-invoker/issues/81 with more details.

After that, I would like to have a deeper look on the options to support Kotlin/Native, and explore the following points:
 - Maybe we could use [Klib](https://kotlinlang.org/docs/tutorials/native/working-with-klib.html) as a deployment unit
- [Gradle support for Kotlin/Native](https://kotlinlang.org/docs/tutorials/native/gradle-for-kotlin-native.html) is IMO a game changer since it allows to deal with dependencies like people are used to in enterprise application world (like Spring) but applied to Native world
 - Another maybe more long term deployment option I would like to explore is [WebAssembly](https://webassembly.org/) which is supported (alpha quality for now) by Kotlin/Native. I am interested by this option because it could be an universal deployment target more suitable to FaaS than Java Bytecode. It could maybe done via https://github.com/projectriff/node-function-invoker even if I think more lightweight runtime less tied to JS would be better. See https://github.com/Geal/serverless-wasm and https://github.com/losfair/IceCore for more details.

**Comment by sdeleuze** [comment]
As discussed on https://github.com/projectriff/java-function-invoker/issues/81, I am going to work on [`kotlin-function-invoker`](https://github.com/sdeleuze/kotlin-function-invoker) dedicated project that will as a first step:
 - Use `java-function-invoker` as a library + `kotlin-runtime` to provide Kotlin/JVM support
 - Support Kotlin [function types](https://kotlinlang.org/docs/reference/lambdas.html#function-types) (`class Greeter : (String) -> String` as a more idiomatic alternative to `class Greeter : Function<String, String>`)
 - Support Kotlin [top level functions](https://kotlinlang.org/docs/reference/functions.html#function-scope) like `go-function-invoker` supports them

When that will work, I would like to explore [Kotlin/Native](https://kotlinlang.org/docs/reference/native-overview.html) support and [scripting](https://github.com/Kotlin/KEEP/blob/scripting/proposals/scripting-support.md) support.

**Comment by fbiville** [comment]
The current plan to support other languages is best described in https://github.com/projectriff/riff/issues/1093. Feel free to comment there for further discussion.
