### ISSUE TITLE
subscribe to metrics for scaling instead of direct kafka events

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff#322]
_From @markfisher on January 25, 2018 16:13_

rather than subscribing directly to the kafka-specific offset topic, we can track the delta between producers and consumers at the sidecar/http-gateway level (including when consumers are activated/deactivated) to drive the scaling algorithm

_Copied from original issue: projectriff/function-controller#7_

**Comment by ericbottard** [comment]
_From @jldec on January 26, 2018 22:38_

counterpart to sidecar metrics publisher https://github.com/projectriff/function-sidecar/issues/41

**Comment by ericbottard** [comment]
_From @jldec on January 26, 2018 23:6_

This work should fix current overscaling behavior observed during kafka rebalancing pauses.

**Comment by glyn** [comment]
PR https://github.com/projectriff/riff/pull/399 is a first attempt at implementing this issue.

# Design of PR 399
Each time a message is produced or consumed on a given input topic, a metrics message is sent to a "metrics" topic. The function controller consumes from the metrics topic and estimates production and consumption rates for each input topic in the hope of using this information to scale the corresponding function(s) to a suitable number of replicas. The goal is to scale to the minimum number of replicas which will prevent the queue of messages in the input topic from growing indefinitely.

# Initial Findings from PR 399

1. **The goal of avoiding checking Kafka's offsets was not achieved.** It was not possible for the function controller to calculate accurate production and consumption counts for an input topic since messages may be consumed more than once before they are committed. Even if it counted only committed messages, it would not be possible to do this accurately (counting before commit could over-estimate in the case of replay; counting after commit could under-estimate in the case of a crash of the function pod between commit and emitting the corresponding metric). Consequently, the function controller still needs to check the offset lag (essentially the queue length) of an input topic to avoid scaling the corresponding functions to zero when production and consumption ceases for a sufficiently long period of time.

2. **Over-scaling can occur due to message bursts.** A message production burst on an input topic can cause the corresponding function(s) to be scaled up to the maximum value (the minimum of `maxReplicas` in the function's configuration and the number of partitions in the input topic). Averaging out message production rates over a longer period could reduce over-scaling, but could impact the responsiveness of scaling up.

3. **Over-scaling can occur due to under-estimation of consumption rates.** The rate at which messages _are_ consumed is measured rather than the rate at which messages _could be_ consumed. One idea for measuring potential consumption rates is to measure the time between a consumer consuming a message and being ready to consume the next message, although this was not implemented in PR 399.

4. **Scaling is not necessarily stable.** Using a metrics channel can introduce an arbitrarily long delay between when metrics are generated and when they are interpreted. This delay could theoretically lead to instability in the scaling behaviour.

# Next Steps

Revisit the design from the perspective of _feedback control_ (1):
* Define a suitable _reference value_ of some measurement that the system should aim for,
* Investigate using a nested control loop (e.g. an inner loop acting on message rates and an outer loop acting on queue length with suitable "proportional", "integral", and "derivative" control).

Investigate simulation of the scaling algorithm as suggested by @jchesterpivotal.

Reference:
1. _Feedback Control for Computer Systems_, Philipp K. Janert, O'Reilly, 2013.

**Comment by glyn** [comment]
As described in the title, this is implemented in a very basic way in 0.0.6.
