### ISSUE TITLE
Function deployments sometimes don't get created or deleted

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#396]
Sometimes my function-controller gets into a state where it does not create or delete the deployment corresponding to a function when I do `riff apply` or `riff delete`. Deleting the function-controller pod (so it restarts) fixes it.

**Comment by jldec** [comment]
Please try to grab the log from the function-controller if this happens again.

**Comment by trisberg** [comment]
I've noticed that a failing function pod takes a ling time to terminate after issuing `riff delete` and the deployment sticks around for that time. So if I run `riff apply` during this "limbo" period I get the function created but there is no deployment created for it since there is already one that is waiting for it's pod to terminate. Once the pod goes away the deployment goes away too, so I'm left with a function without a corresponding deployment. I have to do `riff delete` and `riff apply` again to get back to business.

**Comment by markfisher** [comment]
I think we need to catch the case where a "scale" fails because the underlying Deployment no longer exists, and fallback to creating a Deployment with `replicas=<desired-replicas>`.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
