### ISSUE TITLE
Gateway should return 404 when topic does not exist

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff#410]
```
$ curl localhost:30365/messages/foo -i -d"hello"
HTTP/1.1 200 OK
Date: Mon, 19 Mar 2018 20:07:24 GMT
Content-Length: 32
Content-Type: text/plain; charset=utf-8

Message published to topic: foo

$ kubectl get topic foo
Error from server (NotFound): topics.projectriff.io "foo" not found
```

**Comment by dturanski** [comment]
Related to #373

**Comment by jchesterpivotal** [comment]
After some initial investigation, a few things make this a bit tricky.

1. `sarama.Client` to fetch topics comes back with an empty list of topics, even when topics are present. This means I can't easily compare a topic extracted from a URL path given to `http-gateway` and check if it already exists.
1. We're using the `AsyncProducer`. This means errors are emitted through a channel, rather than for a particular message `.Send()`.
1. No errors get sent for missing topics, because Kafka [will by default](https://kafka.apache.org/documentation/#brokerconfigs) auto-create missing topics (`auto.create.topics.enable=true`).

My current line of attack is to see what happens when Kafka doesn't automatically create topics. There are, of course, unshaved yaks making an appearance.

**Comment by trisberg** [comment]
I think David meant to check for the existence of the Topic resource with the specified name in k8s, and if that doesn't exists return 404 instead of posting the message to the Kafka topic.

**Comment by jchesterpivotal** [comment]
Names are hard tho

**Comment by jchesterpivotal** [comment]
I investigated using `TopicInformer` to dig down and check for the presence of a topic, instead of querying Kafka.

Turns out that this creates a new topic. How I imagine the conversation:

K8s: "Is there a topic called 'foo'?"
Kafka: "There is now."

So we'll still need to configure Kafka to not do that. So far it doesn't seem to pick up the environment variable I provide in the helm chart, so I might grab you to look at that tomorrow, @trisberg.

**Comment by trisberg** [comment]
I don't see why Kafka is involved at all - we should just be able to query the k8s API server to find out if there is a riff topic resource with the name foo. I don't see how a get request could ever create anything on the k8s side of things.

**Comment by jchesterpivotal** [comment]
It's weird to me too -- entirely possible I'm misusing the API.

**Comment by jchesterpivotal** [comment]
It wasn't misuse of the API, it was building the wrong binary. Good times.

The current state of play is that I have code in [my WIP branch](https://github.com/jchesterpivotal/riff/tree/show-404s-for-missing-topics) that a) "works", b) passes existing tests and c) passes a new test.

There's a fair amount left to do, since we're introducing a new concept to the gateway. At the moment my changes are pretty widespread, so I need to look at refactoring opportunities. Some of the behaviour is hardcoded (eg, the "default" namespace). The testing I have relies on a heavy chain of mocks, which makes me uncomfortable. Plus the changes are made to the messages handler but not the requests handler.
