### ISSUE TITLE
function.yaml should be able to add stuff to the deployment spec

### ISSUE THREAD

**Issue by dsyer** [projectriff/riff#413]
E.g. if I want a specific volume mount or service account, I should be able to specify it in the function.yaml and have it passed through to the deployment that is created by riff. Instead the function controller discards anything it doesn't recognize.

**Comment by markfisher** [comment]
IIUC this should already work since we're simply passing the container spec from the function.yaml as-is: https://github.com/projectriff/riff/blob/master/function-controller/pkg/controller/deployer.go#L89

...or are you talking about creating things outside of the scope of the container spec? (like the volume itself, not just the mount)

**Comment by dsyer** [comment]
I wanted to add a serviceAccountName to the pod spec, not the container. Didn't work for me. Volumes are also declared outside the container, right, and that didn't seem to work for me either.

**Comment by markfisher** [comment]
there's an open issue for being able to define a Volume: https://github.com/projectriff/riff/issues/299

**Comment by dsyer** [comment]
OK. Then I guess this is a generalization.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
