### ISSUE TITLE
invoker liveness and readiness 

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#461]
prototyped in node-invoker
- readiness could check gRPC port
- liveness could exec a command to query a new gRPC liveness service

Tasks:
- [ ] create a gRPC liveness service
- [ ] create a client to invoke the gRPC liveness service (exit 0 when alive, otherwise 1)
- [ ] add probes to command invoker
- [ ] add probes to go invoker
- [ ] add probes to java invoker
- [ ] add probes to node invoker
- [ ] ~add probes to python2 invoker~
- [ ] add probes to python3 invoker

**Comment by scothis** [comment]
Liveness and readiness probes are hints to k8s that the container is healthy and able to receive traffic. We've been able to get by without defining the probes since the sidecar pulls traffic from the broker rather than traffic being pushed though a service.

Defining probes is still a best practice and something we should do. Although I'll remove python2 from the list.

**Comment by dturanski** [comment]
Its ok to add probes for k8s but the sidecar or invoker shouldn't be aware of them.

**Comment by scothis** [comment]
>  Its ok to add probes for k8s but the sidecar or invoker, or code running in any app shouldn't be aware of them.

That's not what's being proposed. Probes are by definition scoped to a container.

I have a long [stale branch in the node-function-invoker](https://github.com/scothis/node-function-invoker/blob/probes/lib/grpc.js#L47) that implements a grpc service that indicates if the server/function is healthy. The function is not required to participate, but it can choose to.

**Comment by scothis** [comment]
This issue has gone stale, we're on Knative now! Please reopen if still relevant.
