### ISSUE TITLE
Sidecar errors when running Java functions

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff#572]
The new timeout features for the grpc protocol times out quickly and errors before the Java function has time to start up which could take 10s or more depending on the function.

We need a way to tweak the timeout settings. Maybe introduce an `initialDelay` property.

Once the sidecar container errors it gets restarted but that could cause the back-off-loop to delay the availability fo the functions. Also ugly to see error status and restart count when running the function:

```
$ kubectl get pod -w
NAME                         READY     STATUS    RESTARTS   AGE
uppercase-8545f6fb95-wdqwz   0/2       Pending   0          0s
uppercase-8545f6fb95-wdqwz   0/2       Pending   0         0s
uppercase-8545f6fb95-wdqwz   0/2       ContainerCreating   0         0s
uppercase-8545f6fb95-wdqwz   2/2       Running   0         2s
uppercase-8545f6fb95-wdqwz   1/2       Error     0         10s
uppercase-8545f6fb95-wdqwz   2/2       Running   1         11s
uppercase-8545f6fb95-wdqwz   1/2       Error     1         20s
uppercase-8545f6fb95-wdqwz   1/2       CrashLoopBackOff   1         32s
uppercase-8545f6fb95-wdqwz   2/2       Running   2         33s
uppercase-8545f6fb95-wdqwz   2/2       Terminating   2         47s
uppercase-8545f6fb95-wdqwz   0/2       Terminating   2         50s
```

**Comment by dturanski** [comment]
@trisberg I'm reconsidering the initial delay in favor of making the grpc wait time configurable.  Currently the grpc wait time is set to 100ms with an exponential backoff of 1sec - 4sec between retries. This causes the sidecar to crash if a java app takes > ~7.3 sec to start which is not that unlikely (the Java invoker `uppercase` sample takes about 5 sec.   Talking with @dsyer, he introduced the backoff loop and 100ms wait time. Originally it was set to 60sec. This would cause an unreasonable delay if the function container crashed and recovered, since a new connection is required after the function container recovers, a much shorter wait time eliminated this delay.  Dave's original change also used a fixed backoff which would retry forever, so no significant downside for the java happy path.

Per  @glyn s observation that we don't want to loop forever when the function container is unhealthy , I introduced the current exponential backoff/retry counter.  Testing the initialDelay implementation with the `uppercase` sample, I realized that some unnecessary overhead is incurred if the app takes more than 5 seconds to start.  For example, if it takes 5.2 seconds, the sidecar waits 5 seconds, grpc times out at 5.1 seconds, and then we backoff for 1 sec before attempting to reconnect. So a minimum of 6.1 seconds before the first response. To work around this, in the PR, I set the grpc wait time to the initial delay. This avoids an unnecessary backoff.  But the initial delay is also too pessimistic (Dave's words) if the app takes less then 5 seconds. (The PR requires a fixed initialDelay in the Java invoker).  A better solution is to either make the backoff much more fine grained, e.g. starting at 10ms, or make the grpc wait time configurable. The former is simpler since it requires no configuration and should cover all these cases.  Also, there is a note about about needing to enhance this if windowing is introduced so @ericbottard may want to weigh in here.
