### ISSUE TITLE
riff CLI support for function re-builds and revisions

### ISSUE THREAD

**Issue by jldec** [projectriff/riff#671]
After creating a function, i would like to modify the code, and then use the riff CLI to trigger a rebuild, and point to the new revision.

**Comment by ericbottard** [comment]
I think `compose` should be avoided in the context of functions, because it already has the meaning of `h = f ∘ g`

**Comment by trisberg** [comment]
What about 'construct' or 'make' or 'build' then?

**Comment by jldec** [comment]
+1 for `riff function build`

**Comment by markfisher** [comment]
I think `build` is the most accurate since we rely on the Build CRD to create a service for the provided function code. There is a potential for confusion in that we not only build, but *deploy* that service.

**Comment by scothis** [comment]
I don't think this command should be under function (or build) as it has little to do with functions. We're interacting with a service/configuration at this point. Whether the service has a build or points at a tagged docker repo, the process and effect are identical.

How about:

```
riff service revision create [service name]
```

or maybe:

```
riff revision create [service name]
```

All the command needs to do is update an annotation on the service resource, Knative takes care of the rest.

**Comment by markfisher** [comment]
to clarify, my comment about `riff function build` was in the context of changing the existing name of `riff function create` (which was what I thought Thomas was suggesting, based on the fact that it has no symmetric operations since it's just another way to get to a *service*). Whether we have a separate "update" for revisions is a related but separate decision, and I think I'd lean toward either an explicit noun `riff revision create` or `riff service revise` (seems slightly odd, but it is the actual verb form of "revision")

**Comment by trisberg** [comment]
It's not just triggering a build with new source, it could also be changing env vars that trigger a new revision for a kservice. This whole function/kservice is confusing and I don't think we are clear in how we use either concept and I'm not even sure we shouldn't create configuration/routes for functions instead of a kservice.

**Comment by scothis** [comment]
Thanks, I missed that context shift. Can you open a new issue to track the function/service disparity? My feelings around a command to "re-build" stand.

**Comment by trisberg** [comment]
so we need a way to:

1. kick off a new build pulling latest source from git
    `riff service build greeter`
  we could keep the git sha in a label for the revisionTemplate spec and update that sha to trigger a build

2. update the service settings like env vars
    `riff service patch greeter --env TEST=2`
  this would patch the revisionTemplate,spec.container.env and trigger a rebuild/revision

**Comment by trisberg** [comment]
Only doing #1 for now
