### ISSUE TITLE
`riff image relocate` should always flatten image names

### ISSUE THREAD

**Issue by glyn** [projectriff/riff#901]
Some cases already require us to force flattening. For example, the image name `k8s.gcr.io/fluentd-elasticsearch:v2.0.4` would, without flattening, be relocated to something like `registry.org/reguser:v2.0.4`, which is likely to collide with another similar relocated image, so we force flattening in such cases. However other collisions are likely without flattening.

Another benefit of forcing flattening is that the user no longer has to decide whether to specify `--flatten` based on whether their private registry supports hierarchical path names.

See https://github.com/projectriff/riff/issues/898#issuecomment-432959433 for context.

**Comment by ericbottard** [comment]
Also, since db57f38406599cdb7cf8525cd0b8dc9365549132 we have a better understanding of the role of what we chose to call `image.Digest` (vs `image.Id`). As such, it follows that when an image `docker.io/acme/foobar@sha256:deadbeef` is relocated to `my-registry/evilcorp/foobar`, the `deadbeef` digest doesn't apply anymore (because it is linked to not only the bits of the image, but also the name by which it was known). So it must disappear

**Comment by glyn** [comment]
After discussion with @ericbottard, it does seem a shame to discard the hierarchical path when the registry can support that. Maybe we should make flattening the default but also improve collision avoidance when flattening is not being done.

**Comment by jldec** [comment]
I'd rather spend less time for now, eliminate the non-flattened option, and use what we have for flattening. (if you agree let's change the title of the issue)

**Comment by glyn** [comment]
Fair enough. Split out an issue to support the non-flattened option: https://github.com/projectriff/riff/issues/903.
